
development:
  extends: .deploy
  environment:
    name: development
{%- if cookiecutter.environment_strategy == 'dedicated' %}
  variables:
    SOURCE: {{ cookiecutter.cloud_project }}-development
    TARGET: {{ cookiecutter.cloud_project }}-development
{%- endif %}
  only:
  - merge_requests

integration:
  extends: .deploy
  environment:
    name: integration
{%- if cookiecutter.environment_strategy == 'dedicated' %}
  variables:
    SOURCE: {{ cookiecutter.cloud_project }}-development
    TARGET: {{ cookiecutter.cloud_project }}-integration
{%- endif %}
  only:
  - master

production:
  extends: .deploy
  environment:
    name: production
{%- if cookiecutter.environment_strategy == 'dedicated' %}
  variables:
    SOURCE: {{ cookiecutter.cloud_project }}-integration
    TARGET: {{ cookiecutter.cloud_project }}-production
{%- endif %}
  only:
  - tags
